#define Bash		0
#define Blob_Squish		1
#define BouncyBlock_Bounce		2
#define BouncyJump		3
#define BouncyJump_Small		4
#define BoxHero_Jump		5
#define BoxHero_Land		6
#define Checkpoint		7
#define Coin		8
#define Death_Chime		9
#define Door_Opening		10
#define Door_Slamming		11
#define DoubleJump		12
#define DustCloud_Explode		13
#define ExtraLifeSound		14
#define HeroUnlockedSound		15
#define Jetpack		16
#define Jump		17
#define jump5		18
#define Menu_Back		19
#define Menu_Hover		20
#define Menu_Select		21
#define Menu_Tick		22
#define PerfectSound		23
#define Piece_Explosion_Small		24
#define Pop_1		25
#define Pop_2		26
#define Pop_3		27
#define Record_Scratch		28
