#include <CloudberryKingdom.h>

#include <Content/Texture.h>
#include <Content/Wad.h>
#include <Core.h>
#include <cstdlib>
#include <Graphics/QuadDrawer.h>
#include <Graphics/TextDrawer.h>
#include <Graphics/Types.h>

void CloudberryKingdom::Initialize()
{
	std::vector< std::string > paths;

	/*paths.push_back( "Art/Transparent.png" );
	paths.push_back( "Art/Bob/Accesories/BoxAlone.png" );
	paths.push_back( "Art/Bob/Accesories/BoxAlone_v1.png" );
	paths.push_back( "Art/Bob/Accesories/cart.png" );
	paths.push_back( "Art/Bob/Accesories/Castle_jet_pack.png" );
	paths.push_back( "Art/Bob/Accesories/SingleWing.png" );
	paths.push_back( "Art/Bob/Accesories/Spaceship_Paper.png" );
	paths.push_back( "Art/Bob/Accesories/wings.png" );
	paths.push_back( "Art/Bob/Bouncy/Bob_Horse/Bob_Horse_0000.png" );
	paths.push_back( "Art/Bob/Bouncy/Bob_Horse/Bob_Horse_0001.png" );
	paths.push_back( "Art/Bob/Bouncy/Bob_Horse/Bob_Horse_0002.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Duck/Bob_Box_Duck_0000.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0000.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0001.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0002.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0003.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0004.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Jump/Bob_Box_Jump_0005.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0000.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0001.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0002.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0003.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0004.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Land/Bob_Box_Land_0005.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0000.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0001.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0002.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0003.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0004.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0005.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0006.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0007.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0008.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0009.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0010.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0011.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0012.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0013.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0014.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0015.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0016.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0017.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0018.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0019.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0020.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0021.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0022.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0023.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0024.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0025.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0026.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0027.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0028.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0029.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0030.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0031.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0032.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0033.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0034.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0035.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0036.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0037.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0038.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0039.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0040.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0041.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0042.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0043.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0044.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0045.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0046.png" );
	paths.push_back( "Art/Bob/Box/Bob_Box_Stand/Bob_Box_Stand_0047.png" );
	paths.push_back( "Art/Bob/Cart/Bob_Cart_Duck_0001.png" );
	paths.push_back( "Art/Bob/Cart/Bob_Cart_Jump_0001.png" );
	paths.push_back( "Art/Bob/Cart/Bob_Cart_Stand_0001.png" );
	paths.push_back( "Art/Bob/Classic/v1/Duck/Bob_StandtoDuck_0000.png" );
	paths.push_back( "Art/Bob/Classic/v1/Duck/Bob_StandtoDuck_0001.png" );
	paths.push_back( "Art/Bob/Classic/v1/Duck/Bob_StandtoDuck_0002.png" );
	paths.push_back( "Art/Bob/Classic/v1/Duck/Bob_StandtoDuck_0003.png" );
	paths.push_back( "Art/Bob/Classic/v1/Jump/Bob_Jump_0001.png" );
	paths.push_back( "Art/Bob/Classic/v1/Jump/Bob_Jump_0002.png" );
	paths.push_back( "Art/Bob/Classic/v1/Jump/Bob_Jump_0003.png" );
	paths.push_back( "Art/Bob/Classic/v1/Jump/Bob_Jump_0004.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0001.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0002.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0003.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0004.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0005.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0006.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0007.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0008.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0009.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0010.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0011.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0012.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0013.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0014.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0015.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0016.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0017.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0018.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0019.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0020.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0021.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0022.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0023.png" );
	paths.push_back( "Art/Bob/Classic/v1/Run/Bob_Run_0024.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0001.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0002.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0003.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0004.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0005.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0006.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0007.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0008.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0009.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0010.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0011.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0012.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0013.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0014.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0015.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0016.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0017.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0018.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0019.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0020.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0021.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0022.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0023.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0024.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0025.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0026.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0027.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0028.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0029.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0030.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0031.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0032.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0033.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0034.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0035.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0036.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0037.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0038.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0039.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0040.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0041.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0042.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0043.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0044.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0045.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0046.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0047.png" );
	paths.push_back( "Art/Bob/Classic/v1/Stand/Bob_Stand_0048.png" );
	paths.push_back( "Art/Bob/FacialHair/Beard_Super.png" );
	paths.push_back( "Art/Bob/FacialHair/Goatee_Black.png" );
	paths.push_back( "Art/Bob/FacialHair/Goatee_Blonde.png" );
	paths.push_back( "Art/Bob/FacialHair/Goatee_Brown.png" );
	paths.push_back( "Art/Bob/FacialHair/Goatee_Grey.png" );
	paths.push_back( "Art/Bob/FacialHair/Goatee_Red.png" );
	paths.push_back( "Art/Bob/FacialHair/Moustache_Black.png" );
	paths.push_back( "Art/Bob/FacialHair/Moustache_Blonde.png" );
	paths.push_back( "Art/Bob/FacialHair/Moustache_Brown.png" );
	paths.push_back( "Art/Bob/FacialHair/Moustache_Grey.png" );
	paths.push_back( "Art/Bob/FacialHair/Moustache_Red.png" );
	paths.push_back( "Art/Bob/Wheelie/Bob_Wheel_0000.png" );
	paths.push_back( "Art/Buttons/Keyboard/A_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Backspace_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/B_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/C_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/D_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Enter_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Esc_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/E_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/F_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/G_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/H_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/I_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/J_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/K_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/LeftRight_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/L_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/M_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/N_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/O_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/P_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Q_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/R_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Space_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/S_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/T_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Up_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/U_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/V_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/W_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/X_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Y_Key.png" );
	paths.push_back( "Art/Buttons/Keyboard/Z_Key.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_A.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_B.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_Dir.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_LB.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_LT.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_RB.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_RT.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_Start.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_X.png" );
	paths.push_back( "Art/Buttons/Xbox 360/Xbox_Y.png" );
	paths.push_back( "Art/Characters/Berries/Poses/cb_crying.png" );
	paths.push_back( "Art/Characters/Berries/Poses/cb_enthusiastic.png" );
	paths.push_back( "Art/Characters/Berries/Poses/cb_surprised.png" );
	paths.push_back( "Art/Coins/Checkpoint_v2.png" );
	paths.push_back( "Art/Coins/coin_blue.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00000.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00001.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00002.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00003.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00004.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00005.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00006.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00007.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00008.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00009.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00010.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00011.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00012.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00013.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00014.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00015.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00016.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00017.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00018.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00019.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00020.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00021.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00022.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00023.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00024.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00025.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00026.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00027.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00028.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00029.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00030.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00031.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00032.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00033.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00034.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00035.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00036.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00037.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00038.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00039.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00040.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00041.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00042.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00043.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00044.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00045.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00046.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00047.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00048.png" );
	paths.push_back( "Art/Coins/CoinShimmer/Coin_00049.png" );
	paths.push_back( "Art/Cursor/hand_closed.png" );
	paths.push_back( "Art/Cursor/hand_open.png" );
	paths.push_back( "Art/Effects/Fire.png" );
	paths.push_back( "Art/Effects/Fireball.png" );
	paths.push_back( "Art/Effects/NewLava.png" );
	paths.push_back( "Art/Effects/Pop.png" );
	paths.push_back( "Art/Effects/QM_Happy.png" );
	paths.push_back( "Art/Effects/Smoke.png" );
	paths.push_back( "Art/Effects/Smoke2.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0000.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0001.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0002.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0003.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0004.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0005.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0006.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0007.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0008.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0009.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0010.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0011.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0012.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0013.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0014.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0015.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0016.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0017.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0018.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0019.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0020.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0021.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0022.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0023.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0024.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0025.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0026.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0027.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0028.png" );
	paths.push_back( "Art/Effects/BlobExplosion_v02/BlobExplosion_v02_0029.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0000.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0001.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0002.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0003.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0004.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0005.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0006.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0007.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0008.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0009.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0010.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0011.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0012.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0013.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0014.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0015.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0016.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0017.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0018.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0019.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0020.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0021.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0022.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0023.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0024.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0025.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0026.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0027.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0028.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0029.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0030.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0031.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0032.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0033.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0034.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0035.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0036.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0037.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0038.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0039.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0040.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0041.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0042.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0043.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0044.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0045.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0046.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0047.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0048.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0049.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0050.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0051.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0052.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0053.png" );
	paths.push_back( "Art/Effects/BobExplosion_V01/BobExplosion_V01_0054.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010000.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010001.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010002.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010003.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010004.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010005.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010006.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010007.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010008.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010009.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010010.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010011.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010012.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010013.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010014.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010015.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010016.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010017.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010018.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010019.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010020.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010021.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010022.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010023.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010024.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010025.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010026.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010027.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010028.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010029.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010030.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010031.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v01/CoinCollect_v010032.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0000.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0001.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0002.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0003.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0004.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0005.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0006.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0007.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0008.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0009.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0010.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0011.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0012.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0013.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0014.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0015.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0016.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0017.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0018.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0019.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0020.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0021.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0022.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0023.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0024.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0025.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v02/CoinCollect_v02_0026.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0000.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0001.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0002.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0003.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0004.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0005.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0006.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0007.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0008.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0009.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0010.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0011.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0012.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0013.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0014.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0015.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0016.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0017.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0018.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0019.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0020.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0021.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0022.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0023.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0024.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0025.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectSparkles/CoinCollect_Sparkles_v03_0026.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0000.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0001.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0002.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0003.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0004.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0005.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0006.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0007.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0008.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0009.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0010.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0011.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0012.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0013.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0014.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0015.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0016.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v03/CoinCollectStar/CoinCollect_Star_v03_0017.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0000.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0001.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0002.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0003.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0004.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0005.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0006.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0007.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0008.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0009.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0010.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0011.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0012.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0013.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0014.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0015.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0016.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0017.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0018.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0019.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0020.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0021.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0022.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0023.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0024.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0025.png" );
	paths.push_back( "Art/Effects/CoinCollect/CoinCollect_v04/CoinCollect_v02_0026.png" );
	paths.push_back( "Art/Environments/Rain.png" );
	paths.push_back( "Art/Environments/Snow.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_backdrop.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Backdrop_2.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_chandelier_close.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_chandelier_far.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_lava.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_pillar.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_wall.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/castle_wall_p2.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Center_Frame.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Center_Mask.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Left_Frame.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Left_Mask.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Right_Frame.png" );
	paths.push_back( "Art/Environments/Castle/Background/v2/Castle_Window_Right_Mask.png" );
	paths.push_back( "Art/Environments/Castle/Door/door_castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Door/door_castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Door/Wall_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Blob/Blob_Castle_v1_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Blob/Blob_Castle_v1_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Blob/Blob_Castle_v1_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Blob/Blob_Castle_v1_4.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Bouncy Block/Bouncy_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Bouncy Block/Bouncy_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Bouncy Block/Bouncy_Castle_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Cloud/Cloud_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Elevator/Elevator_Castle_135.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Elevator/Elevator_Castle_190.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Elevator/Elevator_Castle_40.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Elevator/Elevator_Castle_80.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Falling Block/Fblock_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Falling Block/Fblock_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Falling Block/Fblock_Castle_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Firespinner/Firespinner_Base_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Firespinner/Firespinner_Flame_Castle_v1_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Firespinner/Firespinner_Flame_Castle_v1_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Firespinner/Firespinner_Flame_Castle_v1_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Firespinner/Firespinner_Flame_Castle_v1_4.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Floater/Floater_Buzzsaw_Yellow_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Floater/Floater_Chain_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Floater/Floater_Spikey_Castle_v1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Floater/Floater_Spikey_Castle_v2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Flow/Flow_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Flow/Flow_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Flow/Flow_Castle_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Flow/Flow_Icon_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Ghost Block/Ghostblock_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Laser/Laser_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Moving Block/Movingblock_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Moving Block/Movingblock_Castle_135.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Moving Block/Movingblock_Castle_190.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Moving Block/Movingblock_Castle_40.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Moving Block/Movingblock_Castle_80.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Pendulum/Pendulum_Icon_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/SerpentHead_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/SerpentHead_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/Serpent_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/Serpent_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/Serpent_Fish_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Serpent/Serpent_Fish_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/spike_base_castle.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/Spike_Base_Castle_0.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/Spike_Base_Castle_1.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/Spike_Base_Castle_2.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/Spike_Base_Castle_3.png" );
	paths.push_back( "Art/Environments/Castle/Obstacles/Spike/Spike_Castle.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_100.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_1000.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_150.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_250.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_300.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_50.png" );
	paths.push_back( "Art/Environments/Castle/Pillars/Pillar_Castle_600.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_backdrop.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_backdrop_p2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_bottom_1.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_bottom_1_p2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_bottom_2_p1.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_bottom_2_p2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_lightshafts.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_lightshafts_p2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_top_1.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_top_1_p2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_top_2.png" );
	paths.push_back( "Art/Environments/Cave/Background/v3/cave_top_2_p2.png" );
	paths.push_back( "Art/Environments/Cave/Door/door_cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Door/door_cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Door/Wall_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Blob/Blob_Cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Blob/Blob_Cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Blob/Blob_Cave_3.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Blob/Blob_Cave_4.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Bouncy Block/Bouncy_Cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Bouncy Block/Bouncy_Cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Bouncy Block/Bouncy_Cave_3.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Cloud/Cloud_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Elevator/Elevator_Cave_135.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Elevator/Elevator_Cave_190.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Elevator/Elevator_Cave_40.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Elevator/Elevator_Cave_80.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Falling Block/Fblock_Cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Falling Block/Fblock_Cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Falling Block/Fblock_Cave_3.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Floater/Floater_Chain_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Floater/Floater_Rope_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Floater/Floater_Spikey_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Flow/Flow_Cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Flow/Flow_Cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Flow/Flow_Cave_3.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Ghost Block/Ghostblock_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Laser/Laser_Cave.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Moving Block/Movingblock_Cave_135.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Moving Block/Movingblock_Cave_190.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Moving Block/Movingblock_Cave_40.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Moving Block/Movingblock_Cave_80.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Spike/Spike_Base_Cave_0.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Spike/Spike_Base_Cave_1.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Spike/Spike_Base_Cave_2.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Spike/Spike_Base_Cave_3.png" );
	paths.push_back( "Art/Environments/Cave/Obstacles/Spike/spike_cave.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_100.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_1000.png" );
	paths.push_back( ".png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_1000_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_100_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_150.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_150_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_250.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_250_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_300.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_300_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_50.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_50_v3.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_600.png" );
	paths.push_back( "Art/Environments/Cave/Pillars/Pillar_Cave_600_v3.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer2_1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer2_2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer2_3.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer3_1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer3_2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer3_3.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer4.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer4_p2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer5.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_castle_layer5_p2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer1_1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer1_2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer1_3.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer1_4.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer2_1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_1.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_2.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_3.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_4.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_5.png" );
	paths.push_back( "Art/Environments/Cloud/Background/v2/cloud_cloud_layer3_6.png" );
	paths.push_back( "Art/Environments/Cloud/Door/door_cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Door/door_cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Door/Wall_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Blob/Blob_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Blob/Blob_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Blob/Blob_Cloud_3.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Blob/Blob_Cloud_4.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Bouncy Block/Bouncy_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Bouncy Block/Bouncy_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Bouncy Block/Bouncy_Cloud_3.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Cloud/Cloud_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Elevator/Elevator_Cloud_135.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Elevator/Elevator_Cloud_190.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Elevator/Elevator_Cloud_40.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Elevator/Elevator_Cloud_80.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Falling Block/Fblock_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Falling Block/Fblock_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Falling Block/Fblock_Cloud_3.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Base_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Flame_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Flame_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Flame_Cloud_3.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Flame_Cloud_4.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Fire Spinner/Firespinner_Gear_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Floater/Cloud_Chain.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Floater/Floater_Boulder_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Floater/Floater_Rope_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Floater/Floater_Spikey_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Ghost Block/Ghostblock_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Laser/Laser_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Moving Block/MovingBlock_Cloud_135.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Moving Block/MovingBlock_Cloud_190.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Moving Block/MovingBlock_Cloud_40.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Moving Block/MovingBlock_Cloud_80.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Serpent/Serpent_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Serpent/Serpent_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Serpent/Serpent_Fish_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Serpent/Serpent_Fish_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Spike/Spike_Base_Cloud_0.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Spike/Spike_Base_Cloud_1.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Spike/Spike_Base_Cloud_2.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Spike/Spike_Base_Cloud_3.png" );
	paths.push_back( "Art/Environments/Cloud/Obstacles/Spike/Spike_Cloud.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_100.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_1000.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_150.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_250.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_300.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_50.png" );
	paths.push_back( "Art/Environments/Cloud/Pillars/Pillar_Cloud_600.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_backhills.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_backhills_p2.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_backtrees.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_backtrees_p2.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_clouds.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_foretrees.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_foretrees_p2.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_mid.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_mid_p2.png" );
	paths.push_back( "Art/Environments/Forest/Background/v2/forest_sky.png" );
	paths.push_back( "Art/Environments/Forest/Door/door_forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Door/door_forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Door/Wall_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Blob/Blob_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Blob/Blob_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Blob/Blob_Forest_3.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Blob/Blob_Forest_4.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Bouncy Block/Bouncy_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Bouncy Block/Bouncy_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Bouncy Block/Bouncy_Forest_3.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Cloud/Cloud_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Elevator/Elevator_Forest_135.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Elevator/Elevator_Forest_190.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Elevator/Elevator_Forest_40.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Elevator/Elevator_Forest_80.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Falling Block/Fblock_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Falling Block/Fblock_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Falling Block/Fblock_Forest_3.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Firespinner/Firespinner_Base_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Firespinner/Firespinner_Flame_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Firespinner/Firespinner_Flame_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Firespinner/Firespinner_Flame_Forest_3.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Firespinner/Firespinner_Flame_Forest_4.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Floater/Floater_Buzzsaw_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Floater/Floater_Chain_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Floater/Floater_Spikey_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Ghost Block/Ghostblock_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Laser/Laser_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Moving Block/Movingblock_Forest_135_v2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Moving Block/movingblock_forest_150.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Moving Block/Movingblock_Forest_190_v2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Moving Block/Movingblock_Forest_40_v2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Moving Block/Movingblock_Forest_80_v2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Serpent/Serpent_Fish_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Serpent/Serpent_Fish_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Serpent/Serpent_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Serpent/Serpent_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Spike/Spike_Base_Forest_0.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Spike/Spike_Base_Forest_1.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Spike/Spike_Base_Forest_2.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Spike/Spike_Base_Forest_3.png" );
	paths.push_back( "Art/Environments/Forest/Obstacles/Spike/Spike_Forest.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_100.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_1000.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_150.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_250.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_300.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_50.png" );
	paths.push_back( "Art/Environments/Forest/Pillars/Pillar_Forest_600.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backcastles.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backcastles_p2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backdrop.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backdrop_p2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backhills.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backhills2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backhills2_p2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_backhills_p2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_clouds.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_hill1.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_hill2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_hillandtree.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_1.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_2.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_3.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_4.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_5.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_plants_6.png" );
	paths.push_back( "Art/Environments/Hills/Background/v3/hills_rock.png" );
	paths.push_back( "Art/Environments/Hills/Door/door_hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Door/door_hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Door/Wall_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Blob/Blob_Hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Blob/Blob_Hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Blob/Blob_Hills_3.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Blob/Blob_Hills_4.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Bouncy Block/Bouncy_Hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Bouncy Block/Bouncy_Hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Bouncy Block/Bouncy_Hills_3.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Cloud/Cloud_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Elevator/Elevator_Hills_135.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Elevator/Elevator_Hills_190.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Elevator/Elevator_Hills_40.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Elevator/Elevator_Hills_80.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Falling Block/Fblock_Hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Falling Block/Fblock_Hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Falling Block/Fblock_Hills_3.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Firespinner/Firespinner_Base_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Firespinner/Firespinner_Flame_Hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Firespinner/Firespinner_Flame_Hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Firespinner/Firespinner_Flame_Hills_3.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Firespinner/Firespinner_Flame_Hills_4.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Floater/Floater_Boulder_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Floater/Floater_Chain_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Floater/Floater_Rope_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Floater/Floater_Spikey_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Ghost Block/Ghostblock_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Laser/Laser_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Moving Blocks/Movingblock_Hills_135.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Moving Blocks/Movingblock_Hills_190.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Moving Blocks/Movingblock_Hills_40.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Moving Blocks/Movingblock_Hills_80.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Spike/Spike_Base_Hills_0.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Spike/Spike_Base_Hills_1.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Spike/Spike_Base_Hills_2.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Spike/Spike_Base_Hills_3.png" );
	paths.push_back( "Art/Environments/Hills/Obstacles/Spike/Spike_Hills.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_100.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_1000.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_150.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_250.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_300.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_50.png" );
	paths.push_back( "Art/Environments/Hills/Pillars/Pillar_Hills_600.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_backdrop.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_backdrop_p2.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_behind_water_1.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_behind_water_2.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_behind_water_3.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_clouds.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_rock_1.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_rock_2.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_rock_3.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_rock_4.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_rock_5.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_seamonster.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_water_1.png" );
	paths.push_back( "Art/Environments/Sea/Background/v2/sea_water_2.png" );
	paths.push_back( "Art/Environments/Sea/Door/door_sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Door/door_sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Door/Wall_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Blob/Blob_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Blob/Blob_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Blob/Blob_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Blob/Blob_Sea_4.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Bouncy Block/Bouncy_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Bouncy Block/Bouncy_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Bouncy Block/Bouncy_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Cloud/Cloud_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Elevator/Elevator_Sea_135.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Elevator/Elevator_Sea_190.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Elevator/Elevator_Sea_40.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Elevator/Elevator_Sea_80.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Falling Block/Fblock_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Falling Block/Fblock_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Falling Block/Fblock_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Firespinner/Firespinner_Flame_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Firespinner/Firespinner_Flame_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Firespinner/Firespinner_Flame_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Firespinner/Firespinner_Flame_Sea_4.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Firespinner/firespinner_gear_dkpurp.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Floater/Floater_Chain_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Floater/Floater_Spikey_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Floater/Floater_Spikey_Sea_v2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Flow/Flow_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Flow/Flow_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Flow/Flow_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Ghost Block/Ghostblock_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Laser/Laser_Sea.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Moving Block/Movingblock_Sea_135.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Moving Block/Movingblock_Sea_190.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Moving Block/Movingblock_Sea_40.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Moving Block/Movingblock_Sea_80.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Serpent/Serpent_Fish_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Serpent/Serpent_Fish_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Serpent/Serpent_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Serpent/Serpent_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Spike/Spike_Base_Sea_0.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Spike/Spike_Base_Sea_1.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Spike/Spike_Base_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Spike/Spike_Base_Sea_3.png" );
	paths.push_back( "Art/Environments/Sea/Obstacles/Spike/Spike_Sea_2.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_100.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_1000.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_150.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_250.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_300.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_50.png" );
	paths.push_back( "Art/Environments/Sea/Pillars/Pillar_Sea_600.png" );
	paths.push_back( "Art/HeroItems/Capes/CapePic_DWings.png" );
	paths.push_back( "Art/HeroItems/Capes/CapePic_Wings.png" );
	paths.push_back( "Art/HeroItems/Capes/FallingBlock4Cape.png" );
	paths.push_back( "Art/HeroItems/Capes/newwing.png" );
	paths.push_back( "Art/HeroItems/Hats/afro.png" );
	paths.push_back( "Art/HeroItems/Hats/cowboy hat.png" );
	paths.push_back( "Art/HeroItems/Hats/halo.png" );
	paths.push_back( "Art/HeroItems/Hats/HatPic_Horns.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_antlers.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_arrow.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_bag.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_beard.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_bobble.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_brain.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_bunny.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_cone.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_disguise.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_gosu.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_knight.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_miner.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_pirate.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_pope.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_pumkin.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_rastafari.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_rice.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_robinhood.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_santa.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_sombrero.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_tiki.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_toad.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_tophat.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_viking.png" );
	paths.push_back( "Art/HeroItems/Hats/hat_wizard.png" );
	paths.push_back( "Art/HeroItems/Hats/TestHat.png" );
	paths.push_back( "Art/HeroItems/Hats/viking helmet.png" );
	paths.push_back( "Art/LoadScreen_Initial/LoadFill.png" );
	paths.push_back( "Art/LoadScreen_Initial/LoadFill_2.png" );
	paths.push_back( "Art/LoadScreen_Initial/LoadOutline.png" );
	paths.push_back( "Art/LoadScreen_Initial/LoadOutline_2.png" );
	paths.push_back( "Art/LoadScreen_Level/LoadingStrip.png" );
	paths.push_back( "Art/LoadScreen_Level/LoadingStrip2.png" );
	paths.push_back( "Art/Menu/BackArrow2.png" );
	paths.push_back( "Art/Menu/check.png" );
	paths.push_back( "Art/Menu/directionarrow.png" );
	paths.push_back( "Art/Menu/locked.png" );
	paths.push_back( "Art/Menu/uncheck.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1080x840.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1100x900.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1230x740.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1230x740_dark.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1300x660.png" );
	paths.push_back( "Art/Menu/Backplates/backplate_1500x900.png" );
	paths.push_back( "Art/Menu/Backplates/Backplate_Blue.png" );
	paths.push_back( "Art/Menu/CharacterMenu/Arrow_Left.png" );
	paths.push_back( "Art/Menu/CharacterMenu/Arrow_Right.png" );
	paths.push_back( "Art/Menu/CharacterMenu/CharSelect_Backdrop.png" );
	paths.push_back( "Art/Menu/CharacterMenu/CharSelect_BackdropSky.png" );
	paths.push_back( "Art/Menu/CharacterMenu/CharSelect_Frame.png" );
	paths.push_back( "Art/Menu/Controls/ControllerScreen.png" );
	paths.push_back( "Art/Menu/Controls/ControllerScreen_PC.png" );
	paths.push_back( "Art/Menu/CustomLevel/Length.png" );
	paths.push_back( "Art/Menu/CustomLevel/LengthBack.png" );
	paths.push_back( "Art/Menu/Icons/Icon_Checkpoint_v2.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Bouncy.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Box.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Cart.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Classic.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Custom.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Double.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Jetman.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Phase.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Random.png" );
	paths.push_back( "Art/Menu/Icons/Hero/HeroIcon_Wheel.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/CeilingIcon.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/Dodge.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/Icon_FireSpinner.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/Icon_Laser.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/Jump.png" );
	paths.push_back( "Art/Menu/Icons/Upgrades/SpeedIcon.png" );
	paths.push_back( "Art/Menu/Powerups/Powerup_Computer.png" );
	paths.push_back( "Art/Menu/Powerups/Powerup_Path.png" );
	paths.push_back( "Art/Menu/Powerups/Powerup_Slowmo.png" );
	paths.push_back( "Art/Menu/Replay_GUI/End.png" );
	paths.push_back( "Art/Menu/Replay_GUI/Paused.png" );
	paths.push_back( "Art/Menu/Score/Bob_Dead.png" );
	paths.push_back( "Art/Menu/Score/LevelCleared.png" );
	paths.push_back( "Art/Menu/Score/score screen.png" );
	paths.push_back( "Art/Menu/Score/Stopwatch_Black.png" );
	paths.push_back( "Art/Menu/Score/Stopwatch_Gold.png" );
	paths.push_back( "Art/Menu/Score/Stopwatch_White.png" );
	paths.push_back( "Art/Menu/Score/WidePlaque.png" );
	paths.push_back( "Art/Menu/Widgets/ListSelect/ListLeftArrow.png" );
	paths.push_back( "Art/Menu/Widgets/ListSelect/ListRightArrow.png" );
	paths.push_back( "Art/Menu/Widgets/Slider/menuslider_bar.png" );
	paths.push_back( "Art/Menu/Widgets/Slider/menuslider_slider.png" );
	paths.push_back( "Art/Old Art Holdover/blob2_body.png" );
	paths.push_back( "Art/Old Art Holdover/blob2_lwing.png" );
	paths.push_back( "Art/Old Art Holdover/blob2_rwing.png" );
	paths.push_back( "Art/Old Art Holdover/BlobGoo.png" );
	paths.push_back( "Art/Old Art Holdover/BlobGoo2.png" );
	paths.push_back( "Art/Old Art Holdover/BlobGoo3.png" );
	paths.push_back( "Art/Old Art Holdover/BlobGoo4.png" );
	paths.push_back( "Art/Old Art Holdover/BlobGoo5.png" );
	paths.push_back( "Art/Old Art Holdover/blue_small.png" );
	paths.push_back( "Art/Old Art Holdover/checkpoint3.png" );
	paths.push_back( "Art/Old Art Holdover/cloud1.png" );
	paths.push_back( "Art/Old Art Holdover/CoinBlue.png" );
	paths.push_back( "Art/Old Art Holdover/fading block.png" );
	paths.push_back( "Art/Old Art Holdover/FallingBlock1.png" );
	paths.push_back( "Art/Old Art Holdover/FallingBlock2.png" );
	paths.push_back( "Art/Old Art Holdover/score screen_grey.png" );
	paths.push_back( "Art/Old Art Holdover/SpikeyGuy.png" );
	paths.push_back( "Art/Title/BlackSwipe_Vertical.png" );
	paths.push_back( "Art/Title/Title.png" );
	paths.push_back( "Art/Title/Title_Blur.png" );
	paths.push_back( "Art/Title/Title_NoBob_Blur.png" );
	paths.push_back( "Art/Title/Title_NoBob_Brighten.png" );
	paths.push_back( "Art/Title/Title_Princess.png" );
	paths.push_back( "Art/Title/Title_Screen.png" );
	paths.push_back( "Art/Title/Title_Strip.png" );
	paths.push_back( "Art/Title/Title_Teal.png" );
	paths.push_back( "Art/Title/Categories/Arcade/Arcade_Box.png" );
	paths.push_back( "Art/Title/Categories/Arcade/Arcade_BoxLeft.png" );
	paths.push_back( "Art/Title/Categories/Arcade/Scene_Kobbler.png" );
	paths.push_back( "Art/Title/Categories/Arcade/Scene_Kobbler_Blur.png" );
	paths.push_back( "Art/Title/Categories/Story/Scene_Princess.png" );*/

	for( size_t i = 0; i < paths.size(); ++i )
		CONTENT->Load< Texture >( paths[ i ] );
}

void CloudberryKingdom::Update()
{
	ResourcePtr< Texture > texture = CONTENT->Load< Texture >( "Art/Bob_Run_0001.png" );
	ResourcePtr< Texture > background = CONTENT->Load< Texture >( "Art/Title/Title_Screen.png" );
	ResourcePtr< Texture > title = CONTENT->Load< Texture >( "Art/Title/Title.png" );

	SimpleQuad quad;
	quad.Color = Vector4( 1 );
	quad.V[ 0 ] = Vector2( 0, 0 );
	quad.V[ 1 ] = Vector2( 0, 720 );
	quad.V[ 2 ] = Vector2( 1280, 720 );
	quad.V[ 3 ] = Vector2( 1280, 0 );

	quad.T[ 0 ] = Vector2( 0, 0 );
	quad.T[ 1 ] = Vector2( 0, 1 );
	quad.T[ 2 ] = Vector2( 1, 1 );
	quad.T[ 3 ] = Vector2( 1, 0 );

	// Draw background.
	quad.Diffuse = background;
	QUAD_DRAWER->Draw( quad );

	// Draw title.
	quad.Diffuse = title;
	QUAD_DRAWER->Draw( quad );

	TEXT_DRAWER->Draw( "Game Over", Vector2( 0, 0 ) );
}
