/*
 * Take a color and a texture coordinate.  Spit out the color.
 */
varying float2 v_position	: TEXCOORD0;
varying float2 v_texcoord	: TEXCOORD1;
varying float4 v_color		: TEXCOORD2;

uniform sampler2D u_texture	: TEXUNIT0;
uniform float4x4 u_colorMatrix;

float4 main()
{
	float4 texColor = tex2D( u_texture, v_texcoord );
	float4 color = v_color * texColor;
	if( texColor.g > texColor.r + 0.025 && texColor.g > texColor.b + 0.025 )
		color = mul( u_colorMatrix, color );
		
    return color;
}

